{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mediqueue-chart.api.fullname" . }}
  namespace: {{ include "mediqueue-chart.namespace" . }}
  labels:
    {{- include "mediqueue-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.api.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mediqueue-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      annotations:
        {{- include "mediqueue-chart.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "mediqueue-chart.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- include "mediqueue-chart.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "mediqueue-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.repository }}/{{ .Values.api.image.name }}:{{ .Values.api.image.tag | default .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
              protocol: TCP
          {{- if .Values.api.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api.probes.liveness.path }}
              port: {{ .Values.api.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.api.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.liveness.periodSeconds }}
          {{- end }}
          {{- if .Values.api.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.probes.readiness.path }}
              port: {{ .Values.api.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.api.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.readiness.periodSeconds }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "mediqueue-chart.fullname" . }}-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediqueue-chart.postgres.secretName" . }}
                  key: {{ .Values.postgres.auth.secretKey }}
            {{- if .Values.redis.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediqueue-chart.redis.secretName" . }}
                  key: {{ .Values.redis.auth.secretKey }}
            {{- end }}
            - name: REDIS_URL
              value: {{ include "mediqueue-chart.redis.url" . | quote }}
            - name: POSTGRES_URL
              value: {{ include "mediqueue-chart.postgres.url" . | quote }}
            - name: DATABASE_URL
              value: {{ include "mediqueue-chart.postgres.url" . | quote }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
